# Generated by Django 3.2.5 on 2022-09-22 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0002_auto_20220922_1922'),
        ('billing', '0003_auto_20220922_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_date',
            new_name='paid_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customerportal.cartitem'),
        ),
    ]
