# Generated by Django 3.2.5 on 2022-10-02 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
    ]
