# Generated by Django 3.2.5 on 2021-08-21 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accessory_Name', models.CharField(blank=True, choices=[('ALUMINIUM', 'Aluminium'), ('BROADBASE STAND', 'Broadbase Stand'), ('BULB', 'Bulb'), ('NAMETAGS', 'Name Tags')], max_length=25, null=True)),
                ('Accessory_Quantity', models.IntegerField(blank=True, null=True)),
                ('Accessory_Cost', models.IntegerField(blank=True, null=True)),
                ('Item_Date_In', models.DateField(blank=True, null=True)),
                ('Dealer_Phone', models.CharField(blank=True, max_length=15, null=True)),
                ('Dealer_Name', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.CharField(blank=True, max_length=45, null=True)),
                ('Company_Location', models.CharField(max_length=45, null=True)),
                ('Ad_Description', models.TextField(blank=True, null=True)),
                ('Ad_Charges', models.IntegerField(blank=True, null=True)),
                ('Ad_Image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='BrandingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Branding_Item', models.CharField(blank=True, choices=[('TSHIRTS', 'Tshirt'), ('Cap', 'Cap'), ('HOODIES', 'Hoodies'), ('SHIRT', 'Shirt'), ('MUG', 'Mug'), ('REFLECTOR', 'Reflector'), ('OTHER', 'Other')], max_length=10, null=True)),
                ('Size', models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=10, null=True)),
                ('Item_Quantity', models.IntegerField(blank=True, null=True)),
                ('Item_Color', models.CharField(blank=True, choices=[('RED', 'Red'), ('WHITE', 'White'), ('YELLOW', 'Yellow'), ('BLACK', 'Black')], max_length=20, null=True)),
                ('Item_Cost', models.IntegerField(blank=True, null=True)),
                ('Item_Type', models.CharField(blank=True, max_length=20, null=True)),
                ('Item_Date_In', models.DateField(blank=True, null=True)),
                ('Dealer_Phone', models.CharField(blank=True, max_length=15, null=True)),
                ('Dealer_Name', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(blank=True, max_length=45, null=True)),
                ('Last_Name', models.CharField(blank=True, max_length=45, null=True)),
                ('Client_Phone', models.CharField(blank=True, max_length=45, null=True)),
                ('Client_Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Client_Location', models.CharField(blank=True, max_length=45, null=True)),
                ('Client_Designation', models.CharField(blank=True, choices=[('BROKER', 'Broker'), ('REGULAR', 'Regular')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client', models.CharField(blank=True, max_length=45, null=True)),
                ('Product_Size', models.CharField(blank=True, choices=[('A3', 'A3'), ('A4', 'A4')], max_length=50, null=True)),
                ('Client_id', models.CharField(blank=True, max_length=45, null=True)),
                ('Sales_Product', models.CharField(blank=True, max_length=34, null=True)),
                ('Sales_Quantity', models.CharField(blank=True, max_length=34, null=True)),
                ('Sales_Amount_Paid', models.IntegerField(blank=True, null=True)),
                ('Price_Per_Product', models.IntegerField(blank=True, null=True)),
                ('Balance', models.IntegerField(blank=True, null=True)),
                ('Sales_Date', models.DateField(blank=True, null=True)),
                ('Payment_Method', models.CharField(blank=True, choices=[('MPESA', 'M-pesa'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailySalesDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client', models.CharField(blank=True, max_length=45, null=True)),
                ('Product_Size', models.CharField(blank=True, choices=[('A3', 'A3'), ('A4', 'A4')], max_length=50, null=True)),
                ('Client_id', models.CharField(blank=True, max_length=45, null=True)),
                ('Sales_Product', models.CharField(blank=True, max_length=34, null=True)),
                ('Sales_Quantity', models.CharField(blank=True, max_length=34, null=True)),
                ('Sales_Amount', models.IntegerField(blank=True, null=True)),
                ('Balance', models.IntegerField(blank=True, null=True)),
                ('Sales_Date', models.DateField(blank=True, null=True)),
                ('Payment_Method', models.CharField(blank=True, choices=[('MPESA', 'M-pesa'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalPrintingInv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paper_Name', models.CharField(blank=True, choices=[('PHOTOCOPY', 'Photocopy Rim'), ('GLOSSY', 'Glossy Rim'), ('TICTAC', 'TicTac'), ('PHOTOPAPER', 'PhotoPaper rim'), ('IVORY', 'Ivory'), ('PLAINPAPER', 'Plain Paper'), ('PHOTOPAPER', 'Photo Paper'), ('SUBLIMATION', 'Sublimation'), ('EMBOSED', 'Embossed')], max_length=50, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Paper_Cost', models.IntegerField(blank=True, null=True)),
                ('Paper_Size', models.CharField(blank=True, choices=[('A4', 'A4'), ('A3', 'A3')], max_length=5, null=True)),
                ('Item_Date_In', models.DateField(blank=True, null=True)),
                ('Dealer_Phone', models.CharField(blank=True, max_length=15, null=True)),
                ('Dealer_Name', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlatexAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Surname_Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Email_Address', models.EmailField(blank=True, max_length=254, null=True)),
                ('Admin_Phone', models.CharField(blank=True, max_length=13, null=True)),
                ('Admin_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='GlatexContractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone_Number', models.CharField(blank=True, max_length=16, null=True)),
                ('Contractor_Responsibilities', models.CharField(blank=True, choices=[('LARGEFORMAT', 'Large Format'), ('Electricity', 'Electrician')], max_length=30, null=True)),
                ('Contractor_bio', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlatexEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_Id_Number', models.CharField(blank=True, max_length=50, null=True)),
                ('Employee_Birth', models.DateField(blank=True, null=True)),
                ('Employee_Email_Address', models.EmailField(blank=True, max_length=254, null=True)),
                ('Employee_Phone', models.CharField(blank=True, max_length=13, null=True)),
                ('Employee_Department', models.CharField(blank=True, choices=[('DESIGN', 'Design'), ('T_shirt_Printing', 'Tshirt_Printing'), ('FABRICATION', 'Fabrication'), ('RECEPTION', 'Reception'), ('PRINTING', 'Printing')], max_length=30, null=True)),
                ('Employee_Salary', models.CharField(blank=True, max_length=5, null=True)),
                ('Nhif_Status', models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('INACTIVE', 'INACTIVE')], max_length=10, null=True)),
                ('Employee_Status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISCONTINUED', 'Discontinued')], max_length=20, null=True)),
                ('Employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GlatexMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Meeting_Location', models.CharField(blank=True, max_length=25, null=True)),
                ('Meeting_Date', models.DateField(blank=True, null=True)),
                ('Meeting_Purpose', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_Name', models.CharField(blank=True, max_length=45, null=True)),
                ('Delivery_Number', models.CharField(blank=True, max_length=20, null=True)),
                ('Invoice_Total', models.IntegerField(blank=True, null=True)),
                ('Invoice_Date', models.DateField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LargeFormatPrinting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Material_Name', models.CharField(blank=True, choices=[('BANNER', 'Banner'), ('STICKER', 'Sticker'), ('WINDOWGRAPHICS', 'Window Graphics'), ('CLEARSTICKER', 'Clear Sticker'), ('REFLECTIVESTICKER', 'Reflective Sticker')], max_length=20, null=True)),
                ('Item_size', models.CharField(blank=True, max_length=4, null=True)),
                ('Item_Quantity', models.IntegerField(blank=True, null=True)),
                ('Item_Cost', models.IntegerField(blank=True, null=True)),
                ('Item_Date_In', models.DateField(blank=True, null=True)),
                ('Dealer_Phone', models.CharField(blank=True, max_length=15, null=True)),
                ('Dealer_Name', models.CharField(blank=True, max_length=15, null=True)),
                ('Manufacturer_Name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movieexpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Expense_Item', models.CharField(blank=True, max_length=50, null=True)),
                ('Expense_Cost', models.IntegerField(blank=True, null=True)),
                ('Expense_Date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField(blank=True, null=True)),
                ('SalesDate', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PendingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=50, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=19, null=True)),
                ('job_description', models.TextField(blank=True, max_length=56, null=True)),
                ('date_in', models.DateField(blank=True, null=True)),
                ('fullfilment_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlotterMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Material_Name', models.CharField(blank=True, choices=[('VINYL', 'Vinyl'), ('MANILLA', 'Manilla')], max_length=20, null=True)),
                ('Item_Quantity', models.IntegerField(blank=True, null=True)),
                ('Item_Color', models.CharField(blank=True, choices=[('RED', 'Red'), ('WHITE', 'White'), ('YELLOW', 'Yellow'), ('BLACK', 'Black')], max_length=20, null=True)),
                ('Item_Cost', models.IntegerField(blank=True, null=True)),
                ('Dealer_Phone', models.CharField(blank=True, max_length=15, null=True)),
                ('Dealer_Name', models.CharField(blank=True, max_length=15, null=True)),
                ('Item_Date_In', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrintInk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ink_Name', models.CharField(blank=True, max_length=25, null=True)),
                ('Ink_Size', models.CharField(blank=True, max_length=3, null=True)),
                ('Ink_Gadget', models.CharField(blank=True, choices=[('LARGEFORMAT', 'Large Format'), ('DIGITALPRINTER', 'Digital Printer')], max_length=30, null=True)),
                ('Ink_Color', models.CharField(blank=True, max_length=20, null=True)),
                ('Ink_Quantity', models.IntegerField(blank=True, null=True)),
                ('Ink_Cost', models.IntegerField(blank=True, null=True)),
                ('Ink_Date_In', models.DateField(blank=True, null=True)),
                ('Dealer_Phone', models.CharField(blank=True, max_length=15, null=True)),
                ('Dealer_Name', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Name', models.CharField(blank=True, max_length=45, null=True)),
                ('Item_Discount', models.IntegerField(blank=True, null=True)),
                ('Item_cost', models.IntegerField(blank=True, null=True)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('Item_banner_photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SalesAccessoryInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_Name', models.CharField(blank=True, max_length=67, null=True)),
                ('Product', models.CharField(blank=True, max_length=20, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Cost', models.IntegerField(blank=True, null=True)),
                ('saledate', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScreenprintingExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Expense_Item', models.CharField(blank=True, max_length=50, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Expense_Cost', models.IntegerField(blank=True, null=True)),
                ('Expense_Date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Screenprintinginvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_Name', models.CharField(blank=True, max_length=45, null=True)),
                ('Product', models.CharField(blank=True, max_length=20, null=True)),
                ('Invoice_Total', models.IntegerField(blank=True, null=True)),
                ('Invoice_Date', models.DateField(auto_now_add=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScreenprintingSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client', models.CharField(blank=True, max_length=45, null=True)),
                ('Items', models.CharField(blank=True, max_length=45, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Amount_Paid', models.IntegerField(blank=True, null=True)),
                ('Balance', models.IntegerField(blank=True, null=True)),
                ('SalesDate', models.DateField(auto_now_add=True, null=True)),
                ('Payment_Method', models.CharField(blank=True, choices=[('MPESA', 'M-pesa'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_Title', models.CharField(blank=True, max_length=50, null=True)),
                ('Post_Category', models.CharField(choices=[('LARGEFORMAT', 'Large Format'), ('SCREENPRINTING', 'Screen Printing'), ('DIGITALPRINTING', 'Digital Printing')], max_length=20, null=True)),
                ('Post_Description', models.CharField(blank=True, max_length=50, null=True)),
                ('Post_Cost', models.IntegerField(blank=True, null=True)),
                ('Post_Image', models.ImageField(null=True, upload_to='')),
                ('Employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managementportal.glatexemployee')),
            ],
        ),
        migrations.CreateModel(
            name='SalesDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Name', models.CharField(blank=True, max_length=56, null=True)),
                ('Item_Size', models.CharField(blank=True, max_length=10, null=True)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managementportal.dailysales')),
            ],
        ),
        migrations.CreateModel(
            name='ParcelDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=40, null=True)),
                ('receiver_name', models.CharField(blank=True, max_length=40, null=True)),
                ('delivery_location', models.CharField(blank=True, max_length=40, null=True)),
                ('delivery_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('send_date', models.DateField(blank=True, null=True)),
                ('number_plate', models.CharField(blank=True, max_length=10, null=True)),
                ('driver_cell', models.CharField(blank=True, max_length=20, null=True)),
                ('sender', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managementportal.glatexemployee')),
            ],
        ),
        migrations.CreateModel(
            name='Misbehaviour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Misbehaviour_Nature', models.CharField(choices=[('LATENETESS', 'Lateness'), ('Rudeness', 'Rudeness'), ('UNNCESARY DELAYS', 'Unnecessary Delays')], max_length=50, null=True)),
                ('Misbehaviour_Date', models.DateField(null=True)),
                ('Employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='managementportal.glatexemployee')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingMinutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Meeting_Minute', models.TextField(blank=True, null=True)),
                ('Meeting_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managementportal.glatexmeeting')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='managementportal.glatexmeeting')),
                ('members', models.ManyToManyField(blank=True, to='managementportal.GlatexEmployee')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Particular_Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Particular_Size', models.CharField(blank=True, max_length=10, null=True)),
                ('Particular_Amount', models.IntegerField(blank=True, null=True)),
                ('Particular_Invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managementportal.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='GlatexOffice',
            fields=[
                ('Office_Id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Office_Location', models.CharField(blank=True, max_length=20, null=True)),
                ('Office_Cell', models.CharField(blank=True, max_length=13, null=True)),
                ('Office_Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Office_Admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managementportal.glatexadmin')),
            ],
        ),
        migrations.AddField(
            model_name='glatexmeeting',
            name='Office_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managementportal.glatexoffice'),
        ),
        migrations.CreateModel(
            name='GlatexManager',
            fields=[
                ('Manager_Id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('Employee_Id_Number', models.CharField(blank=True, max_length=50, null=True)),
                ('Manager_Email_Address', models.EmailField(blank=True, max_length=254, null=True)),
                ('Manager_Phone', models.CharField(blank=True, max_length=13, null=True)),
                ('Manager_Salary', models.CharField(blank=True, max_length=5, null=True)),
                ('Manager_Office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementportal.glatexoffice')),
            ],
        ),
        migrations.AddField(
            model_name='glatexemployee',
            name='Employee_Office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managementportal.glatexoffice'),
        ),
        migrations.CreateModel(
            name='FabricationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_Name', models.CharField(blank=True, max_length=25, null=True)),
                ('Client_Name', models.CharField(blank=True, max_length=25, null=True)),
                ('Location', models.CharField(blank=True, max_length=50, null=True)),
                ('Print_Material', models.CharField(blank=True, max_length=50, null=True)),
                ('Work_Description', models.CharField(blank=True, max_length=50, null=True)),
                ('Task_Amount', models.IntegerField(blank=True, null=True)),
                ('Payment_Status', models.CharField(blank=True, max_length=20, null=True)),
                ('Task_Location', models.CharField(max_length=30, null=True)),
                ('Fabrication_Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Task_Date', models.DateField(null=True)),
                ('Employees', models.ManyToManyField(blank=True, to='managementportal.GlatexEmployee')),
            ],
        ),
        migrations.CreateModel(
            name='DesignTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_Name', models.CharField(blank=True, max_length=25, null=True)),
                ('Client_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Task_Size', models.CharField(blank=True, max_length=50, null=True)),
                ('Print_Material', models.CharField(blank=True, max_length=50, null=True)),
                ('Task_Amount', models.IntegerField(blank=True, null=True)),
                ('Payment_Status', models.CharField(blank=True, max_length=20, null=True)),
                ('Print_Status', models.CharField(max_length=25, null=True)),
                ('Design_Size', models.CharField(max_length=25, null=True)),
                ('Task_Date', models.DateField(null=True)),
                ('Design_Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Employees', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managementportal.glatexemployee')),
            ],
        ),
        migrations.CreateModel(
            name='DailyExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_Name', models.CharField(blank=True, max_length=56, null=True)),
                ('Expense_Description', models.CharField(blank=True, max_length=50, null=True)),
                ('Expense_Cost', models.IntegerField(blank=True, null=True)),
                ('Expense_Date', models.DateField(blank=True, null=True)),
                ('Employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='managementportal.glatexemployee')),
            ],
        ),
    ]
