# Generated by Django 3.2.5 on 2021-07-30 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accessory_Name', models.CharField(blank=True, choices=[('ALUMINIUM', 'Aluminium'), ('BROADBASE STAND', 'Broadbase Stand'), ('BULB', 'Bulb')], max_length=25, null=True)),
                ('Accessory_Quantity', models.IntegerField(blank=True, null=True)),
                ('Accessory_Cost', models.IntegerField(blank=True, null=True)),
                ('Item_Date_In', models.DateField(blank=True, null=True)),
                ('Dealer_Phone', models.CharField(blank=True, max_length=15, null=True)),
                ('Dealer_Name', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BrandingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Branding_Item', models.CharField(blank=True, choices=[('TSHIRTS', 'Tshirt'), ('Cap', 'Cap'), ('HOODIES', 'Hoodies'), ('SHIRT', 'Shirt'), ('MUG', 'Mug'), ('REFLECTOR', 'Reflector'), ('OTHER', 'Other')], max_length=10, null=True)),
                ('Item_Quantity', models.IntegerField(blank=True, null=True)),
                ('Item_Color', models.CharField(blank=True, choices=[('RED', 'Red'), ('WHITE', 'White'), ('YELLOW', 'Yellow'), ('BLACK', 'Black')], max_length=20, null=True)),
                ('Item_Cost', models.IntegerField(blank=True, null=True)),
                ('Item_Type', models.CharField(blank=True, max_length=20, null=True)),
                ('Item_Date_In', models.DateField(blank=True, null=True)),
                ('Dealer_Phone', models.CharField(blank=True, max_length=15, null=True)),
                ('Dealer_Name', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_Phone', models.CharField(blank=True, max_length=45, null=True)),
                ('Client_Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Client_Location', models.CharField(blank=True, max_length=45, null=True)),
                ('First_Name', models.CharField(blank=True, max_length=45, null=True)),
                ('Client_Designation', models.CharField(blank=True, choices=[('BROKER', 'Broker'), ('REGULAR', 'Regular')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalPrinting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paper_Type', models.CharField(blank=True, choices=[('PHOTOCOPY', 'Photocopy Rim'), ('GLOSSY', 'Glossy Rim'), ('TICTAC', 'TicTac'), ('PHOTOPAPER', 'PhotoPaper rim'), ('IVORY', 'Ivory'), ('OTHERS', 'Others')], max_length=50, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Paper_Cost', models.IntegerField(blank=True, null=True)),
                ('Paper_Size', models.CharField(blank=True, choices=[('A4', 'A4'), ('A3', 'A3')], max_length=5, null=True)),
                ('Item_Date_In', models.DateField(blank=True, null=True)),
                ('Dealer_Phone', models.CharField(blank=True, max_length=15, null=True)),
                ('Dealer_Name', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlatexAdmin',
            fields=[
                ('First_Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Surname_Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Admin_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Email_Address', models.EmailField(blank=True, max_length=254, null=True)),
                ('Admin_Phone', models.CharField(blank=True, max_length=13, null=True)),
                ('Admin_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='GlatexEmployee',
            fields=[
                ('First_Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Surname_Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Employee_Id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('Employee_Email_Address', models.EmailField(blank=True, max_length=254, null=True)),
                ('Employee_Phone', models.CharField(blank=True, max_length=13, null=True)),
                ('Employee_Department', models.CharField(blank=True, choices=[('DESIGN', 'Design'), ('T_shirt_Printing', 'Tshirt_Printing'), ('FABRICATION', 'Fabrication'), ('RECEPTION', 'Reception'), ('PRINTING', 'Printing')], max_length=30, null=True)),
                ('Employee_Salary', models.CharField(blank=True, max_length=5, null=True)),
                ('Nhif_Number', models.CharField(default='None', max_length=10)),
                ('Employee_Status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISCONTINUED', 'Discontinued')], max_length=20, null=True)),
                ('Employee_Admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managementportal.glatexadmin')),
            ],
        ),
        migrations.CreateModel(
            name='GlatexMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Meeting_Venue', models.CharField(blank=True, max_length=30, null=True)),
                ('Meeting_Location', models.CharField(blank=True, max_length=25, null=True)),
                ('Meeting_Date', models.DateField(blank=True, null=True)),
                ('Meeting_Purpose', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client', models.CharField(blank=True, max_length=45, null=True)),
                ('Delivery_Number', models.CharField(blank=True, max_length=20, null=True)),
                ('Particular_Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Invoice_Total', models.IntegerField(blank=True, null=True)),
                ('Invoice_Date', models.DateField(blank=True, null=True)),
                ('Particular_size', models.CharField(blank=True, max_length=20, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LargeFormatPrinting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Material_Name', models.CharField(blank=True, choices=[('BANNER', 'Banner'), ('STICKER', 'Sticker'), ('WINDOWGRAPHICS', 'Window Graphics'), ('CLEARSTICKER', 'Clear Sticker'), ('REFLECTIVESTICKER', 'Reflective Sticker')], max_length=20, null=True)),
                ('Item_size', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('Item_Quantity', models.IntegerField(blank=True, null=True)),
                ('Item_Cost', models.IntegerField(blank=True, null=True)),
                ('Item_Date_In', models.DateField(blank=True, null=True)),
                ('Dealer_Phone', models.CharField(blank=True, max_length=15, null=True)),
                ('Dealer_Name', models.CharField(blank=True, max_length=15, null=True)),
                ('Manufacturer_Name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlotterMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Material_Name', models.CharField(blank=True, choices=[('VINYL', 'Vinyl'), ('MANILLA', 'Manilla')], max_length=20, null=True)),
                ('Item_Qantity', models.IntegerField(blank=True, null=True)),
                ('Item_Color', models.CharField(blank=True, choices=[('RED', 'Red'), ('WHITE', 'White'), ('YELLOW', 'Yellow'), ('BLACK', 'Black')], max_length=20, null=True)),
                ('Item_Cost', models.IntegerField(blank=True, null=True)),
                ('Dealer_Phone', models.CharField(blank=True, max_length=15, null=True)),
                ('Dealer_Name', models.CharField(blank=True, max_length=15, null=True)),
                ('Item_Date_In', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrintInk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ink_Name', models.CharField(blank=True, max_length=25, null=True)),
                ('Ink_Size', models.CharField(blank=True, max_length=3, null=True)),
                ('Ink_Gadget', models.CharField(blank=True, choices=[('LARGEFORMAT', 'Large Format'), ('DIGITALPRINTER', 'Digital Printer')], max_length=30, null=True)),
                ('Ink_Color', models.CharField(blank=True, max_length=20, null=True)),
                ('Ink_Quantity', models.IntegerField(blank=True, null=True)),
                ('Ink_Cost', models.IntegerField(blank=True, null=True)),
                ('Ink_Date_In', models.DateField(blank=True, null=True)),
                ('Dealer_Phone', models.CharField(blank=True, max_length=15, null=True)),
                ('Dealer_Name', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client', models.CharField(blank=True, max_length=45, null=True)),
                ('Client_id', models.CharField(blank=True, max_length=45, null=True)),
                ('Sales_Amount', models.IntegerField(blank=True, null=True)),
                ('Sales_Date', models.DateField(blank=True, null=True)),
                ('Payment_Method', models.CharField(blank=True, choices=[('MPESA', 'M-pesa'), ('CASH', 'Cash')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Post_Category', models.CharField(choices=[('LARGEFORMAT', 'Large Format'), ('SCREENPRINTING', 'Screen Printing'), ('DIGITALPRINTING', 'Digital Printing')], max_length=20, null=True)),
                ('Post_Description', models.CharField(blank=True, max_length=50, null=True)),
                ('Post_Cost', models.IntegerField(blank=True, null=True)),
                ('Post_Image', models.ImageField(null=True, upload_to='')),
                ('Employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managementportal.glatexemployee')),
            ],
        ),
        migrations.CreateModel(
            name='Misbehaviour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Misbehaviour_Nature', models.CharField(max_length=50, null=True)),
                ('Misbehaviour_Date', models.DateField(null=True)),
                ('Employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='managementportal.glatexemployee')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingMinutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Meeting_Agenda', models.CharField(blank=True, max_length=100, null=True)),
                ('Meeting_Venue', models.CharField(blank=True, max_length=30, null=True)),
                ('Meeting_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managementportal.glatexmeeting')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='managementportal.glatexmeeting')),
                ('members', models.ManyToManyField(blank=True, to='managementportal.GlatexEmployee')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceParticulars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Particular_Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Particular_Size', models.CharField(blank=True, max_length=10, null=True)),
                ('Particular_Amount', models.IntegerField(blank=True, null=True)),
                ('Particular_Invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managementportal.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='GlatexOffice',
            fields=[
                ('Office_Id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Office_Location', models.CharField(blank=True, max_length=20, null=True)),
                ('Office_Cell', models.CharField(blank=True, max_length=13, null=True)),
                ('Office_Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Office_Admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managementportal.glatexadmin')),
            ],
        ),
        migrations.AddField(
            model_name='glatexmeeting',
            name='Office_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managementportal.glatexoffice'),
        ),
        migrations.CreateModel(
            name='GlatexManager',
            fields=[
                ('First_Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Surname_Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Manager_Id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('Manager_Email_Address', models.EmailField(blank=True, max_length=254, null=True)),
                ('Manager_Phone', models.CharField(blank=True, max_length=13, null=True)),
                ('Manager_Salary', models.CharField(blank=True, max_length=5, null=True)),
                ('Manager_Office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementportal.glatexoffice')),
            ],
        ),
        migrations.AddField(
            model_name='glatexemployee',
            name='Employee_Office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managementportal.glatexoffice'),
        ),
        migrations.CreateModel(
            name='FabricationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_Name', models.CharField(blank=True, max_length=25, null=True)),
                ('Task_Amount', models.IntegerField(blank=True, null=True)),
                ('Payment_Status', models.CharField(blank=True, max_length=20, null=True)),
                ('Task_Location', models.CharField(max_length=30, null=True)),
                ('Task_Date', models.DateField(null=True)),
                ('Employees', models.ManyToManyField(blank=True, to='managementportal.GlatexEmployee')),
            ],
        ),
        migrations.CreateModel(
            name='DesignTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_Name', models.CharField(blank=True, max_length=25, null=True)),
                ('Task_Amount', models.IntegerField(blank=True, null=True)),
                ('Payment_Status', models.CharField(blank=True, max_length=20, null=True)),
                ('Print_Status', models.CharField(max_length=25, null=True)),
                ('Design_Size', models.CharField(max_length=25, null=True)),
                ('Task_Date', models.DateField(null=True)),
                ('Employees', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managementportal.glatexemployee')),
            ],
        ),
        migrations.CreateModel(
            name='DailyExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Expense_Nature', models.CharField(blank=True, max_length=50, null=True)),
                ('Expense_Cost', models.IntegerField(blank=True, null=True)),
                ('Expense_Date', models.DateField(blank=True, null=True)),
                ('Employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='managementportal.glatexemployee')),
            ],
        ),
    ]
