# Generated by Django 3.2.5 on 2021-08-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysales',
            name='Sales_Amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
