# Generated by Django 3.2.5 on 2022-09-26 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glatexemployee',
            name='Employee',
        ),
    ]
