# Generated by Django 3.2.5 on 2021-08-02 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='Accessory_Name',
            field=models.CharField(blank=True, choices=[('ALUMINIUM', 'Aluminium'), ('BROADBASE STAND', 'Broadbase Stand'), ('BULB', 'Bulb'), ('NAMETAGS', 'Name Tags')], max_length=25, null=True),
        ),
    ]
