# Generated by Django 3.2.5 on 2021-07-30 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glatexmeeting',
            name='Meeting_Venue',
        ),
    ]
