# Generated by Django 3.2.5 on 2021-08-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0002_alter_accessory_accessory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalprinting',
            name='Paper_Type',
        ),
        migrations.AddField(
            model_name='digitalprinting',
            name='Paper_Name',
            field=models.CharField(blank=True, choices=[('PHOTOCOPY', 'Photocopy Rim'), ('GLOSSY', 'Glossy Rim'), ('TICTAC', 'TicTac'), ('PHOTOPAPER', 'PhotoPaper rim'), ('IVORY', 'Ivory'), ('PLAINPAPER', 'Plain Paper'), ('PHOTOPAPER', 'Photo Paper'), ('SUBLIMATION', 'Sublimation'), ('EMBOSED', 'Embossed')], max_length=50, null=True),
        ),
    ]
