# Generated by Django 3.2.5 on 2021-07-30 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0003_glatexcontractors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GlatexContractors',
            new_name='GlatexContractor',
        ),
    ]
