# Generated by Django 3.2.5 on 2021-08-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0003_dailysalesdigital_amount_per_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailysales',
            old_name='Client_id',
            new_name='Client_Phone',
        ),
        migrations.AddField(
            model_name='dailysalesdigital',
            name='Client_Phone',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
