# Generated by Django 3.2.5 on 2021-08-02 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0003_auto_20210802_0940'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DigitalPrinting',
            new_name='DigitalPrintingInventory',
        ),
    ]
