# Generated by Django 3.2.5 on 2021-07-30 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0004_rename_glatexcontractors_glatexcontractor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvoiceParticulars',
            new_name='InvoiceDetails',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='Client',
            new_name='Client_Name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='Particular_Name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='Particular_size',
        ),
    ]
