# Generated by Django 3.2.5 on 2021-08-02 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0004_rename_digitalprinting_digitalprintinginventory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DigitalPrintingInventory',
            new_name='DigitalPrintingInv',
        ),
    ]
