# Generated by Django 3.2.5 on 2021-08-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0005_rename_digitalprintinginventory_digitalprintinginv'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysales',
            name='Sales_Department',
            field=models.CharField(blank=True, choices=[('DESIGN', 'Design'), ('T_shirt_Printing', 'Tshirt_Printing'), ('FABRICATION', 'Fabrication'), ('RECEPTION', 'Reception'), ('PRINTING', 'Printing')], max_length=34, null=True),
        ),
        migrations.AddField(
            model_name='dailysales',
            name='Sales_Product',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
        migrations.AddField(
            model_name='dailysales',
            name='Sales_Quantity',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
    ]
