# Generated by Django 3.2.5 on 2021-08-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0005_alter_dailysales_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyexpenses',
            name='Item_Quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
