# Generated by Django 3.2.5 on 2021-07-30 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0005_auto_20210731_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='largeformatprinting',
            name='Item_size',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
