# Generated by Django 3.2.5 on 2021-08-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0006_auto_20210803_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingitem',
            name='Size',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=10, null=True),
        ),
    ]
