# Generated by Django 3.2.5 on 2021-07-30 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0006_alter_largeformatprinting_item_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingminutes',
            name='Meeting_Agenda',
        ),
        migrations.RemoveField(
            model_name='meetingminutes',
            name='Meeting_Venue',
        ),
        migrations.AddField(
            model_name='meetingminutes',
            name='Meeting_Minute',
            field=models.TextField(blank=True, null=True),
        ),
    ]
