# Generated by Django 3.2.5 on 2021-08-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0006_dailyexpenses_item_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenprintingsales',
            name='Price_Per_Item',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
