# Generated by Django 3.2.5 on 2021-07-30 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0007_auto_20210731_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misbehaviour',
            name='Misbehaviour_Nature',
            field=models.CharField(choices=[('LATENETESS', 'Lateness'), ('Rudeness', 'Rudeness'), ('UNNCESARY DELAYS', 'Unnecessary Delays')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='SalesDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Name', models.CharField(blank=True, max_length=56, null=True)),
                ('Item_Size', models.CharField(blank=True, max_length=10, null=True)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managementportal.sales')),
            ],
        ),
    ]
