# Generated by Django 3.2.5 on 2021-08-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0007_screenprintingsales_price_per_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenprintingsales',
            name='Client_Phone',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
