# Generated by Django 3.2.5 on 2021-08-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0007_brandingitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyexpenses',
            name='Employee_Name',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
    ]
