# Generated by Django 3.2.5 on 2021-07-31 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0008_auto_20210731_0252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.CharField(blank=True, max_length=45, null=True)),
                ('Company_Location', models.CharField(max_length=45, null=True)),
                ('Ad_Description', models.TextField(blank=True, null=True)),
                ('Ad_Charges', models.IntegerField(blank=True, null=True)),
                ('Ad_Image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PendingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=50, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=19, null=True)),
                ('job_description', models.TextField(blank=True, max_length=56, null=True)),
                ('date_in', models.DateField(blank=True, null=True)),
                ('fullfilment_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Name', models.CharField(blank=True, max_length=45, null=True)),
                ('Item_Discount', models.IntegerField(blank=True, null=True)),
                ('Item_cost', models.IntegerField(blank=True, null=True)),
                ('Item_banner_photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ParcelDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=40, null=True)),
                ('delivery_location', models.CharField(blank=True, max_length=40, null=True)),
                ('delivery_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('send_date', models.DateField(blank=True, null=True)),
                ('number_plate', models.CharField(blank=True, max_length=10, null=True)),
                ('driver_cell', models.CharField(blank=True, max_length=20, null=True)),
                ('sender', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managementportal.glatexemployee')),
            ],
        ),
    ]
