# Generated by Django 3.2.5 on 2021-08-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0009_glatexemployee_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glatexemployee',
            name='Employee_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
