# Generated by Django 3.2.5 on 2021-07-31 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0009_ad_parceldelivery_pendingjob_promotionalitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionalitem',
            name='item_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
