# Generated by Django 3.2.5 on 2021-08-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0009_rename_expense_nature_dailyexpenses_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysales',
            name='Product_Size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dailysales',
            name='Payment_Method',
            field=models.CharField(blank=True, choices=[('MPESA', 'M-pesa'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque')], max_length=20, null=True),
        ),
    ]
