# Generated by Django 3.2.5 on 2021-08-06 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0010_auto_20210806_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyexpenses',
            old_name='Item_Name',
            new_name='Expense_Description',
        ),
    ]
