# Generated by Django 3.2.5 on 2021-07-31 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0010_promotionalitem_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='parceldelivery',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
