# Generated by Django 3.2.5 on 2021-07-31 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0011_parceldelivery_receiver_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webpost',
            old_name='Post_Name',
            new_name='Post_Title',
        ),
    ]
