# Generated by Django 3.2.5 on 2021-08-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0011_rename_item_name_dailyexpenses_expense_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saledate', models.DateField(auto_created=True, blank=True, null=True)),
                ('Client_Name', models.CharField(blank=True, max_length=67, null=True)),
                ('Product', models.CharField(blank=True, max_length=20, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
