# Generated by Django 3.2.5 on 2021-08-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0011_auto_20210824_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysalesdigital',
            name='Payment_Method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
