# Generated by Django 3.2.5 on 2021-07-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0012_rename_post_name_webpost_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glatexemployee',
            name='Employee_Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
