# Generated by Django 3.2.5 on 2021-08-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0012_alter_dailysalesdigital_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysales',
            name='Payment_Method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
