# Generated by Django 3.2.5 on 2021-08-12 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0012_salesinventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesinventory',
            old_name='cost',
            new_name='Cost',
        ),
    ]
