# Generated by Django 3.2.5 on 2021-08-12 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0013_rename_cost_salesinventory_cost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalesInventory',
            new_name='SalesAccessoryInventory',
        ),
    ]
