# Generated by Django 3.2.5 on 2021-08-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0014_alter_dailysales_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysalesdigital',
            name='Payment_Method',
            field=models.CharField(blank=True, choices=[('Mpesa', 'Mpesa'), ('Cash', 'Cash'), ('Cheque', 'Cheque')], max_length=20, null=True),
        ),
    ]
