# Generated by Django 3.2.5 on 2021-08-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0014_rename_salesinventory_salesaccessoryinventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField(blank=True, null=True)),
                ('SalesDate', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScreenprintingExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Expense_Item', models.CharField(blank=True, max_length=50, null=True)),
                ('Expense_Cost', models.IntegerField(blank=True, null=True)),
                ('Expense_Date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Screenprintinginvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_Name', models.CharField(blank=True, max_length=45, null=True)),
                ('Product', models.CharField(blank=True, max_length=20, null=True)),
                ('Invoice_Total', models.IntegerField(blank=True, null=True)),
                ('Invoice_Date', models.DateField(auto_now_add=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScreenprintingSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client', models.CharField(blank=True, max_length=45, null=True)),
                ('Items', models.CharField(blank=True, max_length=45, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Amount_Paid', models.IntegerField(blank=True, null=True)),
                ('Balance', models.IntegerField(blank=True, null=True)),
                ('SalesDate', models.DateField(auto_now_add=True, null=True)),
                ('Payment_Method', models.CharField(blank=True, choices=[('MPESA', 'M-pesa'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque')], max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='dailysales',
            name='Sales_Department',
        ),
        migrations.AddField(
            model_name='dailysales',
            name='Balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesaccessoryinventory',
            name='saledate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
