# Generated by Django 3.2.5 on 2021-07-31 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0014_client_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plottermaterial',
            old_name='Item_Qantity',
            new_name='Item_Quantity',
        ),
    ]
