# Generated by Django 3.2.5 on 2021-08-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0015_auto_20210816_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysales',
            name='Category',
            field=models.CharField(blank=True, choices=[('LARGEFORMAT', 'Large Format'), ('DIGITALPRINTING', 'Digital Printing')], max_length=50, null=True),
        ),
    ]
