# Generated by Django 3.2.5 on 2021-08-01 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0015_rename_item_qantity_plottermaterial_item_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sales',
            new_name='DailySales',
        ),
    ]
