# Generated by Django 3.2.5 on 2021-09-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0015_alter_dailysalesdigital_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Town_ClothingExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Cloth_Category', models.CharField(blank=True, max_length=50, null=True)),
                ('Cloth_Type', models.CharField(blank=True, max_length=20, null=True)),
                ('Cloth_Size', models.CharField(blank=True, max_length=20, null=True)),
                ('Cloth_Quantity', models.IntegerField(blank=True, null=True)),
                ('Cost_Per_Cloth', models.IntegerField(blank=True, null=True)),
                ('Shop_Bought', models.CharField(blank=True, max_length=50, null=True)),
                ('Purchase_Date', models.DateField(auto_now=True, null=True)),
                ('Preliminary_Expenses', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
