# Generated by Django 3.2.5 on 2021-09-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0016_town_clothingexpenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='town_clothingexpenses',
            name='Cloth_Color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
