# Generated by Django 3.2.5 on 2021-08-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0016_dailysales_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movieexpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Expense_Item', models.CharField(blank=True, max_length=50, null=True)),
                ('Expense_Cost', models.IntegerField(blank=True, null=True)),
                ('Expense_Date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
