# Generated by Django 3.2.5 on 2021-09-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0017_town_clothingexpenses_cloth_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='town_clothingexpenses',
            name='Requester_Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
