# Generated by Django 3.2.5 on 2021-08-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0017_movieexpenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenprintingexpenses',
            name='Quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
