# Generated by Django 3.2.5 on 2021-09-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0018_town_clothingexpenses_requester_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='town_clothingexpenses',
            name='Total_Cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
