# Generated by Django 3.2.5 on 2021-09-11 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0019_town_clothingexpenses_total_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='town_clothingexpenses',
            old_name='Cloth_Category',
            new_name='Item_Category',
        ),
    ]
