# Generated by Django 3.2.5 on 2021-08-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0019_auto_20210816_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysalesdigital',
            name='Product_Size',
            field=models.CharField(blank=True, choices=[('A3', 'A3'), ('A4', 'A4')], max_length=50, null=True),
        ),
    ]
