# Generated by Django 3.2.5 on 2021-08-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0020_alter_dailysalesdigital_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='designtasks',
            name='Client_Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='designtasks',
            name='Design_Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='designtasks',
            name='Print_Material',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='designtasks',
            name='Task_Size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fabricationtask',
            name='Client_Name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='fabricationtask',
            name='Location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fabricationtask',
            name='Print_Material',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fabricationtask',
            name='Work_Description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
