# Generated by Django 3.2.5 on 2021-09-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0021_auto_20210911_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='largeformatprinting',
            name='Material_Name',
            field=models.CharField(blank=True, choices=[('BANNER', 'Banner'), ('STICKER', 'Sticker'), ('BACKLIT', 'Backlit'), ('WINDOWGRAPHICS', 'Window Graphics'), ('CLEARSTICKER', 'Clear Sticker'), ('REFLECTIVESTICKER', 'Reflective Sticker')], max_length=20, null=True),
        ),
    ]
