# Generated by Django 3.2.5 on 2021-08-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0021_auto_20210818_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricationtask',
            name='Fabrication_Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
