# Generated by Django 3.2.5 on 2021-09-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0022_alter_largeformatprinting_material_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='Accessory_Size',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='accessory',
            name='Accessory_Type',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='Accessory_Name',
            field=models.CharField(blank=True, choices=[('ALUMINIUM', 'Aluminium'), ('BROADBASE STAND', 'Broadbase Stand'), ('BULB', 'Bulb'), ('DX5 INK', 'DX5 INK'), ('PRINTER INK', 'PRINTER INK'), ('TONER', 'TONER')], max_length=25, null=True),
        ),
    ]
