# Generated by Django 3.2.5 on 2021-09-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementportal', '0023_auto_20210919_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='Accessory_Color',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
