# Generated by Django 3.2.5 on 2022-12-02 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='type',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.type'),
        ),
        migrations.AddField(
            model_name='type',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
