# Generated by Django 3.2.5 on 2022-09-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accessory_Name', models.CharField(blank=True, choices=[('ALUMINIUM', 'Aluminium'), ('BROADBASE STAND', 'Broadbase Stand'), ('BULB', 'Bulb')], max_length=25, null=True)),
                ('Accessory_Quantity', models.IntegerField(blank=True, null=True)),
                ('Accessory_Cost', models.IntegerField(blank=True, null=True)),
                ('Item_Date_In', models.DateField(blank=True, null=True)),
                ('Dealer_Phone', models.CharField(blank=True, max_length=15, null=True)),
                ('Dealer_Name', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BrandingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Branding_Item', models.CharField(blank=True, choices=[('TSHIRTS', 'Tshirt'), ('Cap', 'Cap'), ('HOODIES', 'Hoodies'), ('SHIRT', 'Shirt'), ('MUG', 'Mug'), ('REFLECTOR', 'Reflector'), ('OTHER', 'Other')], max_length=10, null=True)),
                ('Item_Quantity', models.IntegerField(blank=True, null=True)),
                ('Item_Color', models.CharField(blank=True, choices=[('RED', 'Red'), ('WHITE', 'White'), ('YELLOW', 'Yellow'), ('BLACK', 'Black')], max_length=20, null=True)),
                ('Item_Cost', models.IntegerField(blank=True, null=True)),
                ('Item_Type', models.CharField(blank=True, max_length=20, null=True)),
                ('Item_Date_In', models.DateField(blank=True, null=True)),
                ('Dealer_Phone', models.CharField(blank=True, max_length=15, null=True)),
                ('Dealer_Name', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalPrinting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paper_Type', models.CharField(blank=True, choices=[('PHOTOCOPY', 'Photocopy Rim'), ('GLOSSY', 'Glossy Rim'), ('TICTAC', 'TicTac'), ('PHOTOPAPER', 'PhotoPaper rim'), ('IVORY', 'Ivory'), ('OTHERS', 'Others')], max_length=50, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Paper_Cost', models.IntegerField(blank=True, null=True)),
                ('Paper_Size', models.CharField(blank=True, choices=[('A4', 'A4'), ('A3', 'A3')], max_length=5, null=True)),
                ('Item_Date_In', models.DateField(blank=True, null=True)),
                ('Dealer_Phone', models.CharField(blank=True, max_length=15, null=True)),
                ('Dealer_Name', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LargeFormatPrinting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Material_Name', models.CharField(blank=True, choices=[('BANNER', 'Banner'), ('STICKER', 'Sticker'), ('WINDOWGRAPHICS', 'Window Graphics'), ('CLEARSTICKER', 'Clear Sticker'), ('REFLECTIVESTICKER', 'Reflective Sticker')], max_length=20, null=True)),
                ('Item_size', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('Item_Quantity', models.IntegerField(blank=True, null=True)),
                ('Item_Cost', models.IntegerField(blank=True, null=True)),
                ('Item_Date_In', models.DateField(blank=True, null=True)),
                ('Dealer_Phone', models.CharField(blank=True, max_length=15, null=True)),
                ('Dealer_Name', models.CharField(blank=True, max_length=15, null=True)),
                ('Manufacturer_Name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlotterMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Material_Name', models.CharField(blank=True, choices=[('VINYL', 'Vinyl'), ('MANILLA', 'Manilla')], max_length=20, null=True)),
                ('Item_Qantity', models.IntegerField(blank=True, null=True)),
                ('Item_Color', models.CharField(blank=True, choices=[('RED', 'Red'), ('WHITE', 'White'), ('YELLOW', 'Yellow'), ('BLACK', 'Black')], max_length=20, null=True)),
                ('Item_Cost', models.IntegerField(blank=True, null=True)),
                ('Dealer_Phone', models.CharField(blank=True, max_length=15, null=True)),
                ('Dealer_Name', models.CharField(blank=True, max_length=15, null=True)),
                ('Item_Date_In', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrintInk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ink_Name', models.CharField(blank=True, max_length=25, null=True)),
                ('Ink_Size', models.CharField(blank=True, max_length=3, null=True)),
                ('Ink_Gadget', models.CharField(blank=True, choices=[('LARGEFORMAT', 'Large Format'), ('DIGITALPRINTER', 'Digital Printer')], max_length=30, null=True)),
                ('Ink_Color', models.CharField(blank=True, max_length=20, null=True)),
                ('Ink_Quantity', models.IntegerField(blank=True, null=True)),
                ('Ink_Cost', models.IntegerField(blank=True, null=True)),
                ('Ink_Date_In', models.DateField(blank=True, null=True)),
                ('Dealer_Phone', models.CharField(blank=True, max_length=15, null=True)),
                ('Dealer_Name', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
