# Generated by Django 3.2.5 on 2022-10-26 00:23

import base.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_serial',
            field=base.fields.UniqueCodeField(blank=True, max_length=10, null=True, verbose_name='order_serial'),
        ),
    ]
