# Generated by Django 3.2.5 on 2021-09-27 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
