# Generated by Django 3.2.5 on 2022-09-26 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0002_auto_20220922_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Cart Item', 'verbose_name_plural': 'Cart Items'},
        ),
        migrations.AlterModelOptions(
            name='mycart',
            options={'verbose_name': 'My Cart', 'verbose_name_plural': 'My Carts'},
        ),
    ]
