# Generated by Django 3.2.5 on 2021-09-27 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0003_category_contactus_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
