# Generated by Django 3.2.5 on 2021-09-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0006_auto_20210927_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
