# Generated by Django 3.2.5 on 2021-10-01 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0008_cart_cartitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='MyCart',
        ),
    ]
