# Generated by Django 3.2.5 on 2021-12-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0016_auto_20211214_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='customerportal.Variation'),
        ),
    ]
