# Generated by Django 3.2.5 on 2022-01-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0017_cartitem_variations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=30, null=True)),
                ('amount_paid', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(blank=True, max_length=80, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
