# Generated by Django 3.2.5 on 2022-01-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0019_auto_20220107_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='item',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
