# Generated by Django 3.2.5 on 2022-01-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0020_alter_payment_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=455),
        ),
    ]
