# Generated by Django 3.2.5 on 2022-01-06 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerportal', '0021_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
